# Generated by Django 5.2.17 on 2026-09-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('Saved', 'Saved'), ('Applied', 'Applied'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Offer', 'Offer')], default='Saved', max_length=20)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=2000)),
                ('location', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
