# Generated by Django 5.2.17 on 2026-09-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
