# Generated by Django 5.2.17 on 2026-09-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_email_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
