# Generated by Django 5.2.17 on 2026-09-30 03:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmailMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_mailbox', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(max_length=255)),
                ('message_id', models.CharField(blank=True, max_length=998)),
                ('sender', models.CharField(max_length=500)),
                ('subject', models.CharField(blank=True, max_length=1000)),
                ('body', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('Pending', 'Pending'), ('Updated', 'Updated'), ('Review', 'Needs review'), ('Ignored', 'Ignored')], default='Pending', max_length=20)),
                ('suggested_status', models.CharField(blank=True, choices=[('Saved', 'Saved'), ('Applied', 'Applied'), ('Interview', 'Interview'), ('Rejected', 'Rejected'), ('Offer', 'Offer')], max_length=20)),
                ('processing_note', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_emails', to='applications.application')),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_emails', to='applications.emailmailbox')),
            ],
            options={
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('mailbox', 'delivery_id'), name='unique_mailbox_email_delivery')],
            },
        ),
    ]
